# Generated by Django 3.1.1 on 2020-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
